version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db/mydatabase
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
      
  redis:
    image: redis:latest

volumes:
  postgres_data:
